# Test
baseURL = 'https://www.ultimatexr.io/'
languageCode = 'en-us'
title = 'UltimateXR | The XR Framework and Toolkit'
theme = 'ultimatexr'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true