baseURL: 'https://www.ultimatexr.io/'
languageCode: en-us
title: UltimateXR
theme: ultimatexr
disablePathToLower: true

menu:
  main:
    - identifier: guides
      name: Guides
      url: /guides/getting-started/
      weight: 10
    - identifier: scripting
      name: API
      url: /api/
      weight: 20
    - name: Community
      url: /community/
      weight: 30
    - name: Enterprise
      url: 'https://www.vrmada.com/en/contact'
      weight: 40
    - name: About
      url: /about/
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
