baseURL = 'https://www.ultimatexr.io/'
languageCode = 'en-us'
title = 'UltimateXR'
theme = 'ultimatexr'
disablePathToLower = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true